import Ddesc2OWL.Ddesc2OWL;
import OWL2DSL.OWL2DSL;
import Onto2OWL.Onto2OWL;
import org.antlr.runtime.RecognitionException;
import org.json.simple.parser.ParseException;
import org.semanticweb.owlapi.model.OWLOntologyCreationException;
import org.semanticweb.owlapi.model.OWLOntologyStorageException;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;

/**
 * Created by jprophet89 on 29/06/14.
 */
public class OWL2GRA  extends javax.swing.JFrame {

    // Execution Variables
    public File onto_file=null;
    public File ontology_file=null;
    public File grammar_file=null;
    public File ddesc_file=null;
    // End of declarations

    // JFRAME Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField name_onto;
    private javax.swing.JTextField name_owl;
    private javax.swing.JTextArea output_ddesc2owl;
    private javax.swing.JTextArea output_onto2dsl;
    private javax.swing.JTextArea output_owl2dsl;
    // End of variables declaration

    /**
     * Creates new form OWL2GRA
     */
    public OWL2GRA() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        name_onto = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        output_onto2dsl = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        name_owl = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        output_owl2dsl = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        output_ddesc2owl = new javax.swing.JTextArea();



        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("File OntoDL::");

        jButton1.setText("Select File");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });

        jLabel2.setText("Name for the Ontology::");

        jButton2.setText("Run Module");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                try {
                    jButton2MousePressed(evt);
                } catch (RecognitionException e) {
                    e.printStackTrace();
                } catch (OWLOntologyCreationException e) {
                    e.printStackTrace();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        });

        output_onto2dsl.setColumns(20);
        output_onto2dsl.setRows(5);
        output_onto2dsl.setSize(this.getWidth(),output_onto2dsl.getHeight());
        jScrollPane1.setViewportView(output_onto2dsl);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jScrollPane1)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel1)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jButton1))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel2)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(name_onto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jButton2))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(jButton1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(name_onto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton2))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
                                .addContainerGap())
        );

        jTabbedPane1.addTab("OntoDL2OWL", jPanel1);

        jLabel3.setText("File OWL::");

        jButton3.setText("Select File");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton3MousePressed(evt);
            }
        });

        jLabel4.setText("Name for the Grammar::");

        jButton4.setText("Run Module");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                try {
                    jButton4MousePressed(evt);
                } catch (OWLOntologyCreationException e) {
                    e.printStackTrace();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        });

        output_owl2dsl.setColumns(20);
        output_owl2dsl.setRows(5);
        output_owl2dsl.setSize(this.getWidth(),output_owl2dsl.getHeight());
        jScrollPane2.setViewportView(output_owl2dsl);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jScrollPane2)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addComponent(jLabel3)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jButton3))
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addComponent(jLabel4)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(name_owl, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jButton4))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(jButton3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(name_owl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton4))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
                                .addContainerGap())
        );

        jTabbedPane1.addTab("OWL2DSL", jPanel2);

        jButton5.setText("Select File");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton5MousePressed(evt);
            }
        });

        jLabel5.setText("File OWL::");

        jButton6.setText("Select File");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton6MousePressed(evt);
            }
        });

        jLabel6.setText("File Grammar::");

        jButton7.setText("Select File");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton7MousePressed(evt);
            }
        });

        jLabel7.setText("File Ddesc::");

        jButton8.setText("Run Module");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                try {
                    jButton8MousePressed(evt);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                } catch (OWLOntologyStorageException e) {
                    e.printStackTrace();
                } catch (OWLOntologyCreationException e) {
                    e.printStackTrace();
                } catch (ParseException e) {
                    e.printStackTrace();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        });

        output_ddesc2owl.setColumns(20);
        output_ddesc2owl.setRows(5);
        output_ddesc2owl.setSize(this.getWidth(),output_ddesc2owl.getHeight());
        jScrollPane3.setViewportView(output_ddesc2owl);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addComponent(jLabel7)
                                                                .addGap(24, 24, 24)
                                                                .addComponent(jButton7))
                                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                                        .addComponent(jLabel5)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(jButton5))
                                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                                        .addComponent(jLabel6)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(jButton6))))
                                                .addGap(67, 67, 67)
                                                .addComponent(jButton8)
                                                .addGap(0, 67, Short.MAX_VALUE))
                                        .addComponent(jScrollPane3))
                                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(jButton5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(jButton6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7)
                                        .addComponent(jButton7)
                                        .addComponent(jButton8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("DDesc2OWL", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 489, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTabbedPane1))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 551, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    /**
     * Buttons Manipulation for the OWL2GRA JFRAME
     * */

    //This Function Select the onto file for the Onto2OWL Module
    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {
        this.jButton1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent ae) {
                JFileChooser fileChooser = new JFileChooser();
                int returnValue = fileChooser.showOpenDialog(null);
                fileChooser.setVisible(true);
                if (returnValue == JFileChooser.APPROVE_OPTION) {
                    File selectedFile = fileChooser.getSelectedFile();
                    onto_file=selectedFile;
                    name_onto.setText(onto_file.getName().substring(0,onto_file.getName().indexOf(".")));
                }
            }
        });
    }
    //This fuctions will run the Onto2OWL Module
    private void jButton2MousePressed(java.awt.event.MouseEvent evt) throws RecognitionException, OWLOntologyCreationException, IOException {
        output_onto2dsl.setText("");
        Onto2OWL onto2OWL=new Onto2OWL();
        String output=onto2OWL.RunModule(onto_file.getAbsolutePath(),name_onto.getText());
        output_onto2dsl.setText(output);
        onto_file=null;
        name_onto.setText("");
    }
    //This Function Select the OWL file for the OWL2DSL Module
    private void jButton3MousePressed(java.awt.event.MouseEvent evt) {
        this.jButton3.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent ae) {
                JFileChooser fileChooser = new JFileChooser();
                int returnValue = fileChooser.showOpenDialog(null);
                fileChooser.setVisible(true);
                if (returnValue == JFileChooser.APPROVE_OPTION) {
                    File selectedFile = fileChooser.getSelectedFile();
                    ontology_file=selectedFile;
                    name_owl.setText(ontology_file.getName().substring(0,ontology_file.getName().indexOf(".")));
                }
            }
        });
    }

    private void jButton4MousePressed(java.awt.event.MouseEvent evt) throws OWLOntologyCreationException, IOException {
        output_owl2dsl.setText("");
        OWL2DSL owl2DSL=new OWL2DSL();
        String output=owl2DSL.RunModule(ontology_file.getAbsolutePath(),name_owl.getText());
        output_owl2dsl.setText(output);
        name_owl.setText("");
        ontology_file=null;
    }
    //This function selects the OWL file for DDesc2OWL Module
    private void jButton5MousePressed(java.awt.event.MouseEvent evt) {
        this.jButton5.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent ae) {
                JFileChooser fileChooser = new JFileChooser();
                int returnValue = fileChooser.showOpenDialog(null);
                fileChooser.setVisible(true);
                if (returnValue == JFileChooser.APPROVE_OPTION) {
                    File selectedFile = fileChooser.getSelectedFile();
                    ontology_file=selectedFile;
                    output_ddesc2owl.setText(output_ddesc2owl.getText()+"\nOWL input::"+ontology_file.getName());
                }
            }
        });
    }
    //This function selects the Grammar file for DDesc2OWL Module
    private void jButton6MousePressed(java.awt.event.MouseEvent evt) {
        this.jButton6.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent ae) {
                JFileChooser fileChooser = new JFileChooser();
                int returnValue = fileChooser.showOpenDialog(null);
                fileChooser.setVisible(true);
                if (returnValue == JFileChooser.APPROVE_OPTION) {
                    File selectedFile = fileChooser.getSelectedFile();
                    grammar_file=selectedFile;
                    output_ddesc2owl.setText(output_ddesc2owl.getText()+"\nGrammar input::"+grammar_file.getName());
                }
            }
        });
    }
    //This function selects the Ddesc file for DDesc2OWL Module
    private void jButton7MousePressed(java.awt.event.MouseEvent evt) {
        this.jButton7.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent ae) {
                JFileChooser fileChooser = new JFileChooser();
                int returnValue = fileChooser.showOpenDialog(null);
                fileChooser.setVisible(true);
                if (returnValue == JFileChooser.APPROVE_OPTION) {
                    File selectedFile = fileChooser.getSelectedFile();
                    ddesc_file=selectedFile;
                    output_ddesc2owl.setText(output_ddesc2owl.getText()+"\nDDesc input::"+ddesc_file.getName());
                }
            }
        });
    }
    // This function Runs the Ddesc2OWL Module
    private void jButton8MousePressed(java.awt.event.MouseEvent evt) throws InterruptedException, OWLOntologyStorageException, OWLOntologyCreationException, ParseException, IOException {
        output_ddesc2owl.setText("Starting...");
        Ddesc2OWL ddesc2OWL=new Ddesc2OWL();
        System.out.println(grammar_file.getParentFile().getPath());
        String output=ddesc2OWL.RunModule(ontology_file.getAbsolutePath(),grammar_file.getAbsolutePath(),ddesc_file.getAbsolutePath(),grammar_file.getParentFile().getPath());
        output_ddesc2owl.setText(output);
        ontology_file=null;
        grammar_file=null;
        ddesc_file=null;
    }

    public static void main(String[] args) throws RecognitionException, OWLOntologyCreationException, IOException, ParseException, InterruptedException, OWLOntologyStorageException {
        if(args.length>0){
            if(args[0].toLowerCase().equals("onto2owl")){
                Onto2OWL onto2OWL=new Onto2OWL();
                String name;
                if(args.length<2){
                    name=args[1];
                    while(name.indexOf("/")>0){
                        name=name.substring(name.indexOf("/"));
                    }
                    name=name.substring(0,name.indexOf("."));
                }else{
                    name=args[2];
                }
                String output=onto2OWL.RunModule(args[1],name);
                System.out.println(output);
            }
            if(args[0].toLowerCase().equals("owl2dsl")){
                OWL2DSL owl2DSL=new OWL2DSL();
                String name;
                if(args.length<2){
                    name=args[1];
                    while(name.indexOf("/")>0){
                        name=name.substring(name.indexOf("/"));
                    }
                    name=name.substring(0,name.indexOf("."));
                }else{
                    name=args[2];
                }
                String output=owl2DSL.RunModule(args[1],name);
                System.out.println(output);
            }
            if(args[0].toLowerCase().equals("ddesc2owl")){
                Ddesc2OWL ddesc2OWL=new Ddesc2OWL();
                File grammarfile=new File(args[2]);
                if(grammarfile.exists()){
                    String output=ddesc2OWL.RunModule(args[1],args[2],args[3], grammarfile.getCanonicalPath());
                    System.out.println(output);
                }
            }
            if(args[0].toLowerCase().equals("help")){
                System.out.println("************************** OWL2Gra **************************");
                System.out.println("* ->Module Onto2OWL                                         *");
                System.out.println("*    argument[0] => onto2owl                                *");
                System.out.println("*    argument[1] => OntoDL file path                        *");
                System.out.println("*    argument[2] => Name for outcome                        *");
                System.out.println("*************************************************************");
                System.out.println("* ->Module OWL2DSL                                          *");
                System.out.println("*    argument[0] => owl2dsl                                 *");
                System.out.println("*    argument[1] => OWL file path                           *");
                System.out.println("*    argument[2] => Name for outcome                        *");
                System.out.println("*************************************************************");
                System.out.println("* ->Module DDesc2OWL                                        *");
                System.out.println("*    argument[0] => ddesc2owl                               *");
                System.out.println("*    argument[1] => OWL file path                           *");
                System.out.println("*    argument[2] => Grammar file path                       *");
                System.out.println("*    argument[3] => DDesc file path                         *");
                System.out.println("*************************************************************");
                System.exit(0);
            }
        }else{
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("teste".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(OWL2GRA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(OWL2GRA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(OWL2GRA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(OWL2GRA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>

        /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new OWL2GRA().setVisible(true);
                }
            });
        }
    }
}
